# Generated by Django 3.1 on 2020-08-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assnment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoutinfrmation',
            name='logoutuserid',
        ),
        migrations.DeleteModel(
            name='information',
        ),
        migrations.DeleteModel(
            name='logoutinfrmation',
        ),
    ]
